#!/usr/bin/env python3
"""Generate explicit read/action allowlists; no arbitrary QObject invocation."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
spec = json.loads((ROOT / 'protocol/ipc-v1.json').read_text())
methods = json.loads((ROOT / 'protocol/DesktopBridgeMethods.json').read_text())
head = '// Generated by tools/ipc/generate_desktop.py; do not edit.\n// clang-format off\n'
server = head + '#pragma once\n#include "sentinel/core/app/ApplicationController.h"\n#include "sentinel/core/app/AppSettings.h"\n#include <QJsonArray>\n#include <QJsonObject>\n#include <QVariant>\n#include <cmath>\nnamespace sentinel::daemon::desktop_contract {\n'
server += 'inline constexpr int pageSize = 24;\ninline constexpr int pages = %d;\n' % ((len(spec['desktop_projection'])+23)//24)
server += 'inline QJsonObject projection(core::ApplicationController* c, int page, bool sessionFields = false) { QJsonObject result; switch(page) {\n'
for index,(name,field) in enumerate(spec['desktop_projection'].items()):
 if index % 24 == 0: server += 'case %d:\n' % (index//24)
 if field.get('eager', False): server += ('if (sessionFields) ' if field['scope']=='session' else 'if (!sessionFields) ') + 'result.insert("%s", QJsonValue::fromVariant(QVariant::fromValue(c->%s())));\n' % (name,name)
 if index % 24 == 23 or index == len(spec['desktop_projection'])-1: server += 'break;\n'
server += '} return result; }\n'
server += 'inline bool validAction(const QString& name, const QJsonArray& args) {\n'
conversion={'QString':'toString()', 'int':'toInt()', 'double':'toDouble()', 'bool':'toBool()', 'QVariantList':'toArray().toVariantList()', 'QVariantMap':'toObject().toVariantMap()', 'QStringList':'toVariant().toStringList()'}
for name,field in spec['desktop_actions'].items():
 server += 'if (name == "%s") { if(args.size() != %d) return false;\n' % (name,len(field['arguments']))
 for i,arg in enumerate(field['arguments']):
  typ=arg['type'];check={'string':f'args[{i}].isString()', 'integer':f'args[{i}].isDouble() && args[{i}].toDouble() == args[{i}].toInt()', 'number':f'args[{i}].isDouble() && std::isfinite(args[{i}].toDouble())', 'boolean':f'args[{i}].isBool()', 'array':f'args[{i}].isArray()', 'object':f'args[{i}].isObject()'}[typ]
  server += f'if (!({check})) return false;\n'
 server += 'return true; }\n'
server += 'return false; }\n'
server += 'inline bool action(core::ApplicationController* c, const QString& name, const QJsonArray& args, QVariant* result) {\n'
conversion={'QString':'toString()', 'int':'toInt()', 'double':'toDouble()', 'bool':'toBool()', 'QVariantList':'toArray().toVariantList()', 'QVariantMap':'toObject().toVariantMap()', 'QStringList':'toVariant().toStringList()'}
for name,field in spec['desktop_actions'].items():
 server += 'if (name == "%s") { if(args.size() != %d) return false;\n' % (name,len(field['arguments']))
 for i,arg in enumerate(field['arguments']):
  typ=arg['type'];check={'string':f'args[{i}].isString()', 'integer':f'args[{i}].isDouble() && args[{i}].toDouble() == args[{i}].toInt()', 'number':f'args[{i}].isDouble() && std::isfinite(args[{i}].toDouble())', 'boolean':f'args[{i}].isBool()', 'array':f'args[{i}].isArray()', 'object':f'args[{i}].isObject()'}[typ]
  server += f'if (!({check})) return false;\n'
 call='c->%s(%s)' % (name,', '.join('args[%d].%s' % (i,conversion[arg['cpp'].replace('const ','').replace('&','').strip()]) for i,arg in enumerate(field['arguments'])))
 server += (call+'; *result = true;' if field['return']=='void' else '*result = '+call+';')+' return true; }\n'
server += 'return false; }\n'
server += 'inline bool globalAction(const QString& name) { return '
server += ' || '.join('name == "%s"' % name for name, field in spec['desktop_actions'].items() if field['scope']=='global')
server += '; }\n'
server += 'inline QJsonObject settings(core::AppSettings* s) { QJsonObject result; if (!s) return result;\n'
for key, field in spec['desktop_settings'].items():
 call='s->%s()' % field['read']
 conversion={'QString':call, 'bool':f'({call} ? QStringLiteral("true") : QStringLiteral("false"))', 'int':f'QString::number({call})', 'double':f'QString::number({call}, \'g\', 17)'}[field['cpp']]
 server += 'result.insert("%s", %s);\n' % (key,conversion)
server += 'return result; }\ninline bool setting(core::AppSettings* s, const QString& key, const QString& value) { if (!s) return false;\n'
for key, field in spec['desktop_settings'].items():
 if not field.get('write'): continue
 typ=field['cpp']
 server += 'if (key == "%s") { ' % key
 if typ=='bool': server += 'if(value != "true" && value != "false") return false; '
 if typ in ['int','double']: server += 'bool valid = false; const auto converted = value.%s(&valid); if (!valid) return false; ' % ('toInt' if typ=='int' else 'toDouble')
 if typ=='double': server += 'if (!std::isfinite(converted)) return false; '
 argument={'QString':'value','bool':'value == "true"','int':'converted','double':'converted'}[typ]
 server += 's->%s(%s); return true; }\n' % (field['write'],argument)
server += 'return false; }\n'
server += 'inline QJsonObject settingsServiceActions() { return QJsonDocument::fromJson(R"json(' + json.dumps(spec['desktop_settings_service'],separators=(',',':')) + ')json").object(); }\n'
server += '}\n// clang-format on\n'

bridge=head
for name,signature in methods.items():
 if name == 'chatHistory': continue
 bridge += 'SENTINEL_DESKTOP_FORWARD(%s)\n' % name
bridge += '// clang-format on\n'
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
for path,content in [('apps/sentinel-daemon/service/DesktopProjection.generated.h',server),('apps/sentinel-desktop/include/sentinel/desktop/DesktopBridge.generated.inc',bridge)]:
 target=ROOT/path
 if args.check:
  if not target.exists() or target.read_text()!=content: raise SystemExit('Stale Desktop contract: '+path)
 elif not target.exists() or target.read_text()!=content: target.write_text(content)
