// Generated by tools/ipc/generate_desktop.py; do not edit.
// clang-format off
#pragma once
#include "sentinel/core/app/ApplicationController.h"
#include "sentinel/core/app/AppSettings.h"
#include <QJsonArray>
#include <QJsonObject>
#include <QVariant>
#include <cmath>
namespace sentinel::daemon::desktop_contract {
inline constexpr int pageSize = 24;
inline constexpr int pages = 28;
inline QJsonObject projection(core::ApplicationController* c, int page, bool sessionFields = false) { QJsonObject result; switch(page) {
case 0:
if (sessionFields) result.insert("activeConversationArchived", QJsonValue::fromVariant(QVariant::fromValue(c->activeConversationArchived())));
if (sessionFields) result.insert("activeConversationStateSummary", QJsonValue::fromVariant(QVariant::fromValue(c->activeConversationStateSummary())));
if (!sessionFields) result.insert("activeRuntimeLocalOnlySummary", QJsonValue::fromVariant(QVariant::fromValue(c->activeRuntimeLocalOnlySummary())));
if (!sessionFields) result.insert("activeRuntimeModelLabel", QJsonValue::fromVariant(QVariant::fromValue(c->activeRuntimeModelLabel())));
if (!sessionFields) result.insert("activeRuntimeProviderLabel", QJsonValue::fromVariant(QVariant::fromValue(c->activeRuntimeProviderLabel())));
if (!sessionFields) result.insert("activeRuntimeReadinessState", QJsonValue::fromVariant(QVariant::fromValue(c->activeRuntimeReadinessState())));
if (!sessionFields) result.insert("activeRuntimeReadinessSummary", QJsonValue::fromVariant(QVariant::fromValue(c->activeRuntimeReadinessSummary())));
if (sessionFields) result.insert("agentAwaitingApproval", QJsonValue::fromVariant(QVariant::fromValue(c->agentAwaitingApproval())));
break;
case 1:
if (sessionFields) result.insert("agentLoopActive", QJsonValue::fromVariant(QVariant::fromValue(c->agentLoopActive())));
if (sessionFields) result.insert("agentStatus", QJsonValue::fromVariant(QVariant::fromValue(c->agentStatus())));
break;
case 2:
if (!sessionFields) result.insert("availableLocalRuntimeSummaries", QJsonValue::fromVariant(QVariant::fromValue(c->availableLocalRuntimeSummaries())));
if (sessionFields) result.insert("chatInputCapabilities", QJsonValue::fromVariant(QVariant::fromValue(c->chatInputCapabilities())));
break;
case 3:
break;
case 4:
break;
case 5:
if (sessionFields) result.insert("conversationHistoryMessageCount", QJsonValue::fromVariant(QVariant::fromValue(c->conversationHistoryMessageCount())));
break;
case 6:
if (sessionFields) result.insert("conversationLastRestoredStatus", QJsonValue::fromVariant(QVariant::fromValue(c->conversationLastRestoredStatus())));
if (sessionFields) result.insert("conversationListCurrentTitle", QJsonValue::fromVariant(QVariant::fromValue(c->conversationListCurrentTitle())));
break;
case 7:
break;
case 8:
if (sessionFields) result.insert("conversationSummaryGenerationStatus", QJsonValue::fromVariant(QVariant::fromValue(c->conversationSummaryGenerationStatus())));
break;
case 9:
break;
case 10:
break;
case 11:
if (!sessionFields) result.insert("installedOllamaModelNames", QJsonValue::fromVariant(QVariant::fromValue(c->installedOllamaModelNames())));
if (sessionFields) result.insert("lastAgentResponse", QJsonValue::fromVariant(QVariant::fromValue(c->lastAgentResponse())));
if (sessionFields) result.insert("latestAgentActivitySummary", QJsonValue::fromVariant(QVariant::fromValue(c->latestAgentActivitySummary())));
if (sessionFields) result.insert("latestApprovalSummary", QJsonValue::fromVariant(QVariant::fromValue(c->latestApprovalSummary())));
break;
case 12:
if (sessionFields) result.insert("latestToolExecutionSummary", QJsonValue::fromVariant(QVariant::fromValue(c->latestToolExecutionSummary())));
if (!sessionFields) result.insert("loadedLMStudioModelNames", QJsonValue::fromVariant(QVariant::fromValue(c->loadedLMStudioModelNames())));
if (!sessionFields) result.insert("localChatInferenceEnabled", QJsonValue::fromVariant(QVariant::fromValue(c->localChatInferenceEnabled())));
if (!sessionFields) result.insert("localChatInferenceStatus", QJsonValue::fromVariant(QVariant::fromValue(c->localChatInferenceStatus())));
if (!sessionFields) result.insert("localChatSendAvailabilitySummary", QJsonValue::fromVariant(QVariant::fromValue(c->localChatSendAvailabilitySummary())));
if (!sessionFields) result.insert("localChatSendAvailable", QJsonValue::fromVariant(QVariant::fromValue(c->localChatSendAvailable())));
if (sessionFields) result.insert("localInferenceRuntimeState", QJsonValue::fromVariant(QVariant::fromValue(c->localInferenceRuntimeState())));
if (sessionFields) result.insert("localInferenceStatus", QJsonValue::fromVariant(QVariant::fromValue(c->localInferenceStatus())));
break;
case 13:
if (sessionFields) result.insert("localInferenceStreamingText", QJsonValue::fromVariant(QVariant::fromValue(c->localInferenceStreamingText())));
break;
case 14:
break;
case 15:
if (!sessionFields) result.insert("modelCapabilityCompatibilitySummary", QJsonValue::fromVariant(QVariant::fromValue(c->modelCapabilityCompatibilitySummary())));
if (!sessionFields) result.insert("modelCapabilitySettings", QJsonValue::fromVariant(QVariant::fromValue(c->modelCapabilitySettings())));
break;
case 16:
if (!sessionFields) result.insert("ollamaHealthStatus", QJsonValue::fromVariant(QVariant::fromValue(c->ollamaHealthStatus())));
if (!sessionFields) result.insert("ollamaHealthSummary", QJsonValue::fromVariant(QVariant::fromValue(c->ollamaHealthSummary())));
if (!sessionFields) result.insert("ollamaModelCount", QJsonValue::fromVariant(QVariant::fromValue(c->ollamaModelCount())));
if (!sessionFields) result.insert("ollamaModelNames", QJsonValue::fromVariant(QVariant::fromValue(c->ollamaModelNames())));
break;
case 17:
if (!sessionFields) result.insert("promptContextInjectionEnabled", QJsonValue::fromVariant(QVariant::fromValue(c->promptContextInjectionEnabled())));
break;
case 18:
break;
case 19:
if (!sessionFields) result.insert("runtimeProviderCapabilitySummaries", QJsonValue::fromVariant(QVariant::fromValue(c->runtimeProviderCapabilitySummaries())));
if (!sessionFields) result.insert("runtimeProviderCardSummaries", QJsonValue::fromVariant(QVariant::fromValue(c->runtimeProviderCardSummaries())));
break;
case 20:
if (!sessionFields) result.insert("selectableRuntimeProviderIds", QJsonValue::fromVariant(QVariant::fromValue(c->selectableRuntimeProviderIds())));
if (!sessionFields) result.insert("selectableRuntimeProviderLabels", QJsonValue::fromVariant(QVariant::fromValue(c->selectableRuntimeProviderLabels())));
if (!sessionFields) result.insert("selectedLocalModel", QJsonValue::fromVariant(QVariant::fromValue(c->selectedLocalModel())));
if (!sessionFields) result.insert("selectedLocalModelMetadataSummary", QJsonValue::fromVariant(QVariant::fromValue(c->selectedLocalModelMetadataSummary())));
if (!sessionFields) result.insert("selectedLocalModelStatus", QJsonValue::fromVariant(QVariant::fromValue(c->selectedLocalModelStatus())));
if (!sessionFields) result.insert("selectedLocalModelSummary", QJsonValue::fromVariant(QVariant::fromValue(c->selectedLocalModelSummary())));
if (!sessionFields) result.insert("selectedModelCapabilityLabels", QJsonValue::fromVariant(QVariant::fromValue(c->selectedModelCapabilityLabels())));
if (!sessionFields) result.insert("selectedRuntimeProvider", QJsonValue::fromVariant(QVariant::fromValue(c->selectedRuntimeProvider())));
break;
case 21:
break;
case 22:
if (!sessionFields) result.insert("semanticPromptInclusionEnabled", QJsonValue::fromVariant(QVariant::fromValue(c->semanticPromptInclusionEnabled())));
break;
case 23:
break;
case 24:
break;
case 25:
break;
case 26:
break;
case 27:
if (!sessionFields) result.insert("currentWorkspaceName", QJsonValue::fromVariant(QVariant::fromValue(c->currentWorkspaceName())));
break;
} return result; }
inline bool validAction(const QString& name, const QJsonArray& args) {
if (name == "approveMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "archiveConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "archiveMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "clearChat") { if(args.size() != 0) return false;
return true; }
if (name == "clearConversationSearch") { if(args.size() != 0) return false;
return true; }
if (name == "clearLocalMemoryRecall") { if(args.size() != 0) return false;
return true; }
if (name == "clearMemory") { if(args.size() != 0) return false;
return true; }
if (name == "clearPersistentPermissions") { if(args.size() != 0) return false;
return true; }
if (name == "configureMcpServers") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "configureSpeechTts") { if(args.size() != 3) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
if (!(args[2].isString())) return false;
return true; }
if (name == "configureWebSearch") { if(args.size() != 3) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
if (!(args[2].isDouble() && args[2].toDouble() == args[2].toInt())) return false;
return true; }
if (name == "createMemoryCandidateFromConversationText") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "duplicateConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "exportTranscript") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "generatePiperTtsFile") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "pinConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "recallLocalMemory") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "refreshModelDiscovery") { if(args.size() != 0) return false;
return true; }
if (name == "refreshOllamaStatus") { if(args.size() != 0) return false;
return true; }
if (name == "rejectMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "remember") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
return true; }
if (name == "renameConversation") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
return true; }
if (name == "requestMemoryCandidateCommit") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "requestPermanentDeleteConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "resetMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "resetModelCapabilityOverrides") { if(args.size() != 0) return false;
return true; }
if (name == "revokePersistentPermission") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "searchConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setAgentAutonomousMode") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "setLlamaCppEndpoint") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setLmStudioEndpoint") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setLocalChatInferenceEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "setLocalInferenceMaxTokens") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && args[0].toDouble() == args[0].toInt())) return false;
return true; }
if (name == "setLocalInferenceStreamingEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "setLocalInferenceTemperature") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && std::isfinite(args[0].toDouble()))) return false;
return true; }
if (name == "setLocalInferenceTimeoutMs") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && args[0].toDouble() == args[0].toInt())) return false;
return true; }
if (name == "setLocalInferenceTopP") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && std::isfinite(args[0].toDouble()))) return false;
return true; }
if (name == "setModelCapabilityNumberOverride") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isDouble() && args[1].toDouble() == args[1].toInt())) return false;
return true; }
if (name == "setModelCapabilityOverride") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
return true; }
if (name == "setOllamaEndpoint") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setPiperBinaryPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setPiperFileOutputExecutionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "setPiperModelPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setPromptContextInjectionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "setRoutingModeByName") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setSelectedLocalModel") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setSelectedRuntimeProvider") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setSemanticPromptInclusionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "setSemanticProvider") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
return true; }
if (name == "setToolPermissionPolicyState") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setWhisperBinaryPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setWhisperModelPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "setWhisperTranscriptionExecutionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
return true; }
if (name == "unarchiveConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
if (name == "unpinConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
return true; }
return false; }
inline bool action(core::ApplicationController* c, const QString& name, const QJsonArray& args, QVariant* result) {
if (name == "approveMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->approveMemoryCandidate(args[0].toString()); return true; }
if (name == "archiveConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->archiveConversation(args[0].toString()); return true; }
if (name == "archiveMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->archiveMemoryCandidate(args[0].toString()); return true; }
if (name == "clearChat") { if(args.size() != 0) return false;
*result = c->clearChat(); return true; }
if (name == "clearConversationSearch") { if(args.size() != 0) return false;
c->clearConversationSearch(); *result = true; return true; }
if (name == "clearLocalMemoryRecall") { if(args.size() != 0) return false;
c->clearLocalMemoryRecall(); *result = true; return true; }
if (name == "clearMemory") { if(args.size() != 0) return false;
*result = c->clearMemory(); return true; }
if (name == "clearPersistentPermissions") { if(args.size() != 0) return false;
*result = c->clearPersistentPermissions(); return true; }
if (name == "configureMcpServers") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->configureMcpServers(args[0].toString()); *result = true; return true; }
if (name == "configureSpeechTts") { if(args.size() != 3) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
if (!(args[2].isString())) return false;
c->configureSpeechTts(args[0].toString(), args[1].toString(), args[2].toString()); *result = true; return true; }
if (name == "configureWebSearch") { if(args.size() != 3) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
if (!(args[2].isDouble() && args[2].toDouble() == args[2].toInt())) return false;
c->configureWebSearch(args[0].toString(), args[1].toString(), args[2].toInt()); *result = true; return true; }
if (name == "createMemoryCandidateFromConversationText") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->createMemoryCandidateFromConversationText(args[0].toString()); return true; }
if (name == "duplicateConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->duplicateConversation(args[0].toString()); return true; }
if (name == "exportTranscript") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->exportTranscript(args[0].toString()); return true; }
if (name == "generatePiperTtsFile") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->generatePiperTtsFile(args[0].toString()); return true; }
if (name == "pinConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->pinConversation(args[0].toString()); return true; }
if (name == "recallLocalMemory") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->recallLocalMemory(args[0].toString()); return true; }
if (name == "refreshModelDiscovery") { if(args.size() != 0) return false;
c->refreshModelDiscovery(); *result = true; return true; }
if (name == "refreshOllamaStatus") { if(args.size() != 0) return false;
c->refreshOllamaStatus(); *result = true; return true; }
if (name == "rejectMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->rejectMemoryCandidate(args[0].toString()); return true; }
if (name == "remember") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
c->remember(args[0].toString(), args[1].toString()); *result = true; return true; }
if (name == "renameConversation") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
*result = c->renameConversation(args[0].toString(), args[1].toString()); return true; }
if (name == "requestMemoryCandidateCommit") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->requestMemoryCandidateCommit(args[0].toString()); return true; }
if (name == "requestPermanentDeleteConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->requestPermanentDeleteConversation(args[0].toString()); return true; }
if (name == "resetMemoryCandidate") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->resetMemoryCandidate(args[0].toString()); return true; }
if (name == "resetModelCapabilityOverrides") { if(args.size() != 0) return false;
c->resetModelCapabilityOverrides(); *result = true; return true; }
if (name == "revokePersistentPermission") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->revokePersistentPermission(args[0].toString()); return true; }
if (name == "searchConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->searchConversation(args[0].toString()); return true; }
if (name == "setAgentAutonomousMode") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setAgentAutonomousMode(args[0].toBool()); *result = true; return true; }
if (name == "setLlamaCppEndpoint") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setLlamaCppEndpoint(args[0].toString()); *result = true; return true; }
if (name == "setLmStudioEndpoint") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setLmStudioEndpoint(args[0].toString()); *result = true; return true; }
if (name == "setLocalChatInferenceEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setLocalChatInferenceEnabled(args[0].toBool()); *result = true; return true; }
if (name == "setLocalInferenceMaxTokens") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && args[0].toDouble() == args[0].toInt())) return false;
c->setLocalInferenceMaxTokens(args[0].toInt()); *result = true; return true; }
if (name == "setLocalInferenceStreamingEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setLocalInferenceStreamingEnabled(args[0].toBool()); *result = true; return true; }
if (name == "setLocalInferenceTemperature") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && std::isfinite(args[0].toDouble()))) return false;
c->setLocalInferenceTemperature(args[0].toDouble()); *result = true; return true; }
if (name == "setLocalInferenceTimeoutMs") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && args[0].toDouble() == args[0].toInt())) return false;
c->setLocalInferenceTimeoutMs(args[0].toInt()); *result = true; return true; }
if (name == "setLocalInferenceTopP") { if(args.size() != 1) return false;
if (!(args[0].isDouble() && std::isfinite(args[0].toDouble()))) return false;
c->setLocalInferenceTopP(args[0].toDouble()); *result = true; return true; }
if (name == "setModelCapabilityNumberOverride") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isDouble() && args[1].toDouble() == args[1].toInt())) return false;
*result = c->setModelCapabilityNumberOverride(args[0].toString(), args[1].toInt()); return true; }
if (name == "setModelCapabilityOverride") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
*result = c->setModelCapabilityOverride(args[0].toString(), args[1].toString()); return true; }
if (name == "setOllamaEndpoint") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setOllamaEndpoint(args[0].toString()); *result = true; return true; }
if (name == "setPiperBinaryPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setPiperBinaryPath(args[0].toString()); *result = true; return true; }
if (name == "setPiperFileOutputExecutionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setPiperFileOutputExecutionEnabled(args[0].toBool()); *result = true; return true; }
if (name == "setPiperModelPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setPiperModelPath(args[0].toString()); *result = true; return true; }
if (name == "setPromptContextInjectionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setPromptContextInjectionEnabled(args[0].toBool()); *result = true; return true; }
if (name == "setRoutingModeByName") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setRoutingModeByName(args[0].toString()); *result = true; return true; }
if (name == "setSelectedLocalModel") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setSelectedLocalModel(args[0].toString()); *result = true; return true; }
if (name == "setSelectedRuntimeProvider") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setSelectedRuntimeProvider(args[0].toString()); *result = true; return true; }
if (name == "setSemanticPromptInclusionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setSemanticPromptInclusionEnabled(args[0].toBool()); *result = true; return true; }
if (name == "setSemanticProvider") { if(args.size() != 2) return false;
if (!(args[0].isString())) return false;
if (!(args[1].isString())) return false;
c->setSemanticProvider(args[0].toString(), args[1].toString()); *result = true; return true; }
if (name == "setToolPermissionPolicyState") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setToolPermissionPolicyState(args[0].toString()); *result = true; return true; }
if (name == "setWhisperBinaryPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setWhisperBinaryPath(args[0].toString()); *result = true; return true; }
if (name == "setWhisperModelPath") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
c->setWhisperModelPath(args[0].toString()); *result = true; return true; }
if (name == "setWhisperTranscriptionExecutionEnabled") { if(args.size() != 1) return false;
if (!(args[0].isBool())) return false;
c->setWhisperTranscriptionExecutionEnabled(args[0].toBool()); *result = true; return true; }
if (name == "unarchiveConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->unarchiveConversation(args[0].toString()); return true; }
if (name == "unpinConversation") { if(args.size() != 1) return false;
if (!(args[0].isString())) return false;
*result = c->unpinConversation(args[0].toString()); return true; }
return false; }
inline bool globalAction(const QString& name) { return name == "configureMcpServers" || name == "configureSpeechTts" || name == "configureWebSearch" || name == "refreshModelDiscovery" || name == "refreshOllamaStatus" || name == "setAgentAutonomousMode" || name == "setLlamaCppEndpoint" || name == "setLmStudioEndpoint" || name == "setLocalChatInferenceEnabled" || name == "setLocalInferenceMaxTokens" || name == "setLocalInferenceStreamingEnabled" || name == "setLocalInferenceTemperature" || name == "setLocalInferenceTimeoutMs" || name == "setLocalInferenceTopP" || name == "setModelCapabilityNumberOverride" || name == "setModelCapabilityOverride" || name == "setOllamaEndpoint" || name == "setPiperBinaryPath" || name == "setPiperFileOutputExecutionEnabled" || name == "setPiperModelPath" || name == "setPromptContextInjectionEnabled" || name == "setRoutingModeByName" || name == "setSelectedLocalModel" || name == "setSelectedRuntimeProvider" || name == "setSemanticPromptInclusionEnabled" || name == "setSemanticProvider" || name == "setToolPermissionPolicyState" || name == "setWhisperBinaryPath" || name == "setWhisperModelPath" || name == "setWhisperTranscriptionExecutionEnabled"; }
inline QJsonObject settings(core::AppSettings* s) { QJsonObject result; if (!s) return result;
result.insert("themeName", s->themeName());
result.insert("configurationProfile", s->configurationProfile());
result.insert("appLanguage", s->appLanguage());
result.insert("routingMode", s->routingModeName());
result.insert("ollamaEndpoint", s->ollamaEndpoint());
result.insert("lmStudioEndpoint", s->lmStudioEndpoint());
result.insert("llamaCppEndpoint", s->llamaCppEndpoint());
result.insert("cloudApiEndpoint", s->cloudApiEndpoint());
result.insert("webSearchProvider", s->webSearchProvider());
result.insert("webSearchMaxResults", QString::number(s->webSearchMaxResults()));
result.insert("mcpServersJson", s->mcpServersJson());
result.insert("semanticProvider", s->semanticProvider());
result.insert("semanticEmbeddingModel", s->semanticEmbeddingModel());
result.insert("selectedRuntimeProvider", s->selectedRuntimeProvider());
result.insert("selectedCloudProvider", s->selectedCloudProvider());
result.insert("localInferenceTimeoutMs", QString::number(s->localInferenceTimeoutMs()));
result.insert("localInferenceTemperature", QString::number(s->localInferenceTemperature(), 'g', 17));
result.insert("localInferenceTopP", QString::number(s->localInferenceTopP(), 'g', 17));
result.insert("localInferenceMaxTokens", QString::number(s->localInferenceMaxTokens()));
result.insert("promptContextInjectionEnabled", (s->promptContextInjectionEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("semanticPromptInclusionEnabled", (s->semanticPromptInclusionEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("contextExplainabilityVisible", (s->contextExplainabilityVisible() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("companionEnabled", (s->companionEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("developerModeEnabled", (s->developerModeEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("agentAutonomousMode", (s->agentAutonomousMode() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("piperBinaryPath", s->piperBinaryPath());
result.insert("piperModelPath", s->piperModelPath());
result.insert("whisperBinaryPath", s->whisperBinaryPath());
result.insert("whisperModelPath", s->whisperModelPath());
result.insert("piperFileOutputExecutionEnabled", (s->piperFileOutputExecutionEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("selectedTtsEngine", s->selectedTtsEngine());
result.insert("kokoroModelPath", s->kokoroModelPath());
result.insert("kokoroVoice", s->kokoroVoice());
result.insert("activeConversationId", s->activeConversationId());
result.insert("selectedWorkspaceId", s->selectedWorkspaceId());
result.insert("defaultWorkspaceId", s->defaultWorkspaceId());
result.insert("workspaceCatalogJson", s->workspaceCatalogJson());
result.insert("localKnowledgeBaseEnabled", (s->localKnowledgeBaseEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("retrievalExplainabilityEnabled", (s->retrievalExplainabilityEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("attachmentBehavior", s->attachmentBehavior());
result.insert("exportDefaultFormat", s->exportDefaultFormat());
result.insert("exportIncludeTimestamps", (s->exportIncludeTimestamps() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("exportIncludeCitations", (s->exportIncludeCitations() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("exportAnonymizeNames", (s->exportAnonymizeNames() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("exportIncludeModelMetadata", (s->exportIncludeModelMetadata() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("responseProfileInstructions", s->responseProfileInstructions());
result.insert("selectedSkillProfile", s->selectedSkillProfile());
result.insert("defaultPermissionPolicyState", s->defaultPermissionPolicyState());
result.insert("updateCheckPolicy", s->updateCheckPolicy());
result.insert("updateCheckUrl", s->updateCheckUrl());
result.insert("notificationPolicy", s->notificationPolicy());
result.insert("onboardingComplete", (s->onboardingComplete() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("onboardingUseCase", s->onboardingUseCase());
result.insert("selectedSystemMode", s->selectedSystemMode());
result.insert("onboardingAiProvider", s->onboardingAiProvider());
result.insert("recoveryDraftText", s->recoveryDraftText());
result.insert("reducedMotionEnabled", (s->reducedMotionEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("highContrastEnabled", (s->highContrastEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("uiDensity", s->uiDensity());
result.insert("notificationCenterJson", s->notificationCenterJson());
result.insert("updateWorkflowState", s->updateWorkflowState());
result.insert("controlledAgentTasksJson", s->controlledAgentTasksJson());
result.insert("controlledAgentPermissionsJson", s->controlledAgentPermissionsJson());
result.insert("notifyModelDownloads", (s->notifyModelDownloads() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("notifyModelRemovals", (s->notifyModelRemovals() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("notifyAgentResponses", (s->notifyAgentResponses() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("notifySystemUpdates", (s->notifySystemUpdates() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("soundEffectsEnabled", (s->soundEffectsEnabled() ? QStringLiteral("true") : QStringLiteral("false")));
result.insert("networkMode", s->networkMode());
return result; }
inline bool setting(core::AppSettings* s, const QString& key, const QString& value) { if (!s) return false;
if (key == "themeName") { s->setThemeName(value); return true; }
if (key == "configurationProfile") { s->setConfigurationProfile(value); return true; }
if (key == "appLanguage") { s->setAppLanguage(value); return true; }
if (key == "routingMode") { s->setRoutingModeName(value); return true; }
if (key == "ollamaEndpoint") { s->setOllamaEndpoint(value); return true; }
if (key == "lmStudioEndpoint") { s->setLmStudioEndpoint(value); return true; }
if (key == "llamaCppEndpoint") { s->setLlamaCppEndpoint(value); return true; }
if (key == "cloudApiEndpoint") { s->setCloudApiEndpoint(value); return true; }
if (key == "webSearchProvider") { s->setWebSearchProvider(value); return true; }
if (key == "webSearchMaxResults") { bool valid = false; const auto converted = value.toInt(&valid); if (!valid) return false; s->setWebSearchMaxResults(converted); return true; }
if (key == "mcpServersJson") { s->setMcpServersJson(value); return true; }
if (key == "semanticProvider") { s->setSemanticProvider(value); return true; }
if (key == "semanticEmbeddingModel") { s->setSemanticEmbeddingModel(value); return true; }
if (key == "selectedRuntimeProvider") { s->setSelectedRuntimeProvider(value); return true; }
if (key == "selectedCloudProvider") { s->setSelectedCloudProvider(value); return true; }
if (key == "localInferenceTimeoutMs") { bool valid = false; const auto converted = value.toInt(&valid); if (!valid) return false; s->setLocalInferenceTimeoutMs(converted); return true; }
if (key == "localInferenceTemperature") { bool valid = false; const auto converted = value.toDouble(&valid); if (!valid) return false; if (!std::isfinite(converted)) return false; s->setLocalInferenceTemperature(converted); return true; }
if (key == "localInferenceTopP") { bool valid = false; const auto converted = value.toDouble(&valid); if (!valid) return false; if (!std::isfinite(converted)) return false; s->setLocalInferenceTopP(converted); return true; }
if (key == "localInferenceMaxTokens") { bool valid = false; const auto converted = value.toInt(&valid); if (!valid) return false; s->setLocalInferenceMaxTokens(converted); return true; }
if (key == "promptContextInjectionEnabled") { if(value != "true" && value != "false") return false; s->setPromptContextInjectionEnabled(value == "true"); return true; }
if (key == "semanticPromptInclusionEnabled") { if(value != "true" && value != "false") return false; s->setSemanticPromptInclusionEnabled(value == "true"); return true; }
if (key == "contextExplainabilityVisible") { if(value != "true" && value != "false") return false; s->setContextExplainabilityVisible(value == "true"); return true; }
if (key == "companionEnabled") { if(value != "true" && value != "false") return false; s->setCompanionEnabled(value == "true"); return true; }
if (key == "developerModeEnabled") { if(value != "true" && value != "false") return false; s->setDeveloperModeEnabled(value == "true"); return true; }
if (key == "agentAutonomousMode") { if(value != "true" && value != "false") return false; s->setAgentAutonomousMode(value == "true"); return true; }
if (key == "piperBinaryPath") { s->setPiperBinaryPath(value); return true; }
if (key == "piperModelPath") { s->setPiperModelPath(value); return true; }
if (key == "whisperBinaryPath") { s->setWhisperBinaryPath(value); return true; }
if (key == "whisperModelPath") { s->setWhisperModelPath(value); return true; }
if (key == "piperFileOutputExecutionEnabled") { if(value != "true" && value != "false") return false; s->setPiperFileOutputExecutionEnabled(value == "true"); return true; }
if (key == "selectedTtsEngine") { s->setSelectedTtsEngine(value); return true; }
if (key == "kokoroModelPath") { s->setKokoroModelPath(value); return true; }
if (key == "kokoroVoice") { s->setKokoroVoice(value); return true; }
if (key == "activeConversationId") { s->setActiveConversationId(value); return true; }
if (key == "selectedWorkspaceId") { s->setSelectedWorkspaceId(value); return true; }
if (key == "defaultWorkspaceId") { s->setDefaultWorkspaceId(value); return true; }
if (key == "workspaceCatalogJson") { s->setWorkspaceCatalogJson(value); return true; }
if (key == "localKnowledgeBaseEnabled") { if(value != "true" && value != "false") return false; s->setLocalKnowledgeBaseEnabled(value == "true"); return true; }
if (key == "retrievalExplainabilityEnabled") { if(value != "true" && value != "false") return false; s->setRetrievalExplainabilityEnabled(value == "true"); return true; }
if (key == "attachmentBehavior") { s->setAttachmentBehavior(value); return true; }
if (key == "exportDefaultFormat") { s->setExportDefaultFormat(value); return true; }
if (key == "exportIncludeTimestamps") { if(value != "true" && value != "false") return false; s->setExportIncludeTimestamps(value == "true"); return true; }
if (key == "exportIncludeCitations") { if(value != "true" && value != "false") return false; s->setExportIncludeCitations(value == "true"); return true; }
if (key == "exportAnonymizeNames") { if(value != "true" && value != "false") return false; s->setExportAnonymizeNames(value == "true"); return true; }
if (key == "exportIncludeModelMetadata") { if(value != "true" && value != "false") return false; s->setExportIncludeModelMetadata(value == "true"); return true; }
if (key == "responseProfileInstructions") { s->setResponseProfileInstructions(value); return true; }
if (key == "selectedSkillProfile") { s->setSelectedSkillProfile(value); return true; }
if (key == "defaultPermissionPolicyState") { s->setDefaultPermissionPolicyState(value); return true; }
if (key == "updateCheckPolicy") { s->setUpdateCheckPolicy(value); return true; }
if (key == "updateCheckUrl") { s->setUpdateCheckUrl(value); return true; }
if (key == "notificationPolicy") { s->setNotificationPolicy(value); return true; }
if (key == "onboardingComplete") { if(value != "true" && value != "false") return false; s->setOnboardingComplete(value == "true"); return true; }
if (key == "onboardingUseCase") { s->setOnboardingUseCase(value); return true; }
if (key == "selectedSystemMode") { s->setSelectedSystemMode(value); return true; }
if (key == "onboardingAiProvider") { s->setOnboardingAiProvider(value); return true; }
if (key == "recoveryDraftText") { s->setRecoveryDraftText(value); return true; }
if (key == "reducedMotionEnabled") { if(value != "true" && value != "false") return false; s->setReducedMotionEnabled(value == "true"); return true; }
if (key == "highContrastEnabled") { if(value != "true" && value != "false") return false; s->setHighContrastEnabled(value == "true"); return true; }
if (key == "uiDensity") { s->setUiDensity(value); return true; }
if (key == "notificationCenterJson") { s->setNotificationCenterJson(value); return true; }
if (key == "updateWorkflowState") { s->setUpdateWorkflowState(value); return true; }
if (key == "controlledAgentTasksJson") { s->setControlledAgentTasksJson(value); return true; }
if (key == "controlledAgentPermissionsJson") { s->setControlledAgentPermissionsJson(value); return true; }
if (key == "notifyModelDownloads") { if(value != "true" && value != "false") return false; s->setNotifyModelDownloads(value == "true"); return true; }
if (key == "notifyModelRemovals") { if(value != "true" && value != "false") return false; s->setNotifyModelRemovals(value == "true"); return true; }
if (key == "notifyAgentResponses") { if(value != "true" && value != "false") return false; s->setNotifyAgentResponses(value == "true"); return true; }
if (key == "notifySystemUpdates") { if(value != "true" && value != "false") return false; s->setNotifySystemUpdates(value == "true"); return true; }
if (key == "soundEffectsEnabled") { if(value != "true" && value != "false") return false; s->setSoundEffectsEnabled(value == "true"); return true; }
return false; }
inline QJsonObject settingsServiceActions() { return QJsonDocument::fromJson(R"json({"productSettings":{"query":true,"arguments":[]},"productSettingsSections":{"query":true,"arguments":[]},"setProductSetting":{"query":false,"arguments":["string","value"]},"resetProductSetting":{"query":false,"arguments":["string"]},"resetProductSettingsSection":{"query":false,"arguments":["integer"]},"clearWorkspaceSettingOverride":{"query":false,"arguments":["string","string"]},"providerSettingsState":{"query":true,"arguments":["string"]},"extensionSettingsState":{"query":true,"arguments":["string"]},"performExtensionSettingsAction":{"query":false,"arguments":["string","integer"]},"speechSettingsState":{"query":true,"arguments":[]},"securitySettingsState":{"query":true,"arguments":[]},"productPrivacyState":{"query":true,"arguments":[]},"productRecoveryState":{"query":true,"arguments":[]},"productBackupAvailability":{"query":true,"arguments":[]},"exportProductBackup":{"query":false,"arguments":["array"]},"importProductBackup":{"query":false,"arguments":["string","array","boolean"]},"clearProductData":{"query":false,"arguments":["string"]},"runProductMaintenance":{"query":false,"arguments":[]},"resolveInterruptedModelOperation":{"query":false,"arguments":["string"]},"clearProductCredential":{"query":false,"arguments":["string"]},"setProductProviderCredential":{"query":false,"arguments":["string","string"]},"setProductPluginCredential":{"query":false,"arguments":["string","string","string"]},"clearProductPluginCredential":{"query":false,"arguments":["string","string"]}})json").object(); }
}
// clang-format on
