// clang-format off
// Generated by tools/ipc/generate.py; do not edit.
#pragma once
#include <QJsonObject>
#include <QJsonArray>
#include <QString>
namespace sentinel::daemon::protocol {
inline constexpr int major = 1;
inline constexpr int minor = 0;
inline constexpr int max_frame_bytes = 262144;
inline constexpr int max_pending_bytes = 1048576;
enum class Command { hello, daemon_status, daemon_shutdown, model_list, model_current, session_list, session_create, session_attach, chat_send, agent_start, run_cancel, approval_respond };
inline QJsonArray capabilities() { return {QStringLiteral("chat"), QStringLiteral("agent"), QStringLiteral("approval"), QStringLiteral("sessions"), QStringLiteral("events")}; }
inline QJsonObject commands() { return {
{QStringLiteral("hello"), QJsonObject{{QStringLiteral("client_id"), QStringLiteral("string")}, {QStringLiteral("major"), QStringLiteral("integer")}, {QStringLiteral("minor"), QStringLiteral("integer")}, {QStringLiteral("capabilities"), QStringLiteral("array")}}},
{QStringLiteral("daemon.status"), QJsonObject{}},
{QStringLiteral("daemon.shutdown"), QJsonObject{}},
{QStringLiteral("model.list"), QJsonObject{}},
{QStringLiteral("model.current"), QJsonObject{}},
{QStringLiteral("session.list"), QJsonObject{}},
{QStringLiteral("session.create"), QJsonObject{{QStringLiteral("title"), QStringLiteral("string")}}},
{QStringLiteral("session.attach"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("chat.send"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("text"), QStringLiteral("string")}}},
{QStringLiteral("agent.start"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("text"), QStringLiteral("string")}}},
{QStringLiteral("run.cancel"), QJsonObject{{QStringLiteral("run_id"), QStringLiteral("string")}}},
{QStringLiteral("approval.respond"), QJsonObject{{QStringLiteral("run_id"), QStringLiteral("string")}, {QStringLiteral("approval_id"), QStringLiteral("string")}, {QStringLiteral("allow"), QStringLiteral("boolean")}}},
}; }
}
// clang-format on
