// clang-format off
// Generated by tools/ipc/generate.py; do not edit.
#pragma once
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonDocument>
#include <QString>
namespace sentinel::daemon::protocol {
inline constexpr int major = 1;
inline constexpr int minor = 1;
inline constexpr int max_frame_bytes = 262144;
inline constexpr int max_pending_bytes = 1048576;
enum class Command { hello, daemon_status, daemon_shutdown, model_list, model_current, session_list, session_create, session_attach, chat_send, agent_start, run_cancel, approval_respond, desktop_projection, desktop_action, session_messages, model_select, chat_regenerate, chat_retry, chat_edit, desktop_settings, desktop_setting, model_helper_state, model_helper_action, desktop_settings_service, terminal_state, workspace_files, workspace_select, workspace_root, workspace_changes, workspace_create, provider_select, terminal_attach, voice_state, voice_action, voice_audio };
inline QJsonArray capabilities() { return {QStringLiteral("chat"), QStringLiteral("agent"), QStringLiteral("approval"), QStringLiteral("sessions"), QStringLiteral("events"), QStringLiteral("desktop-projection"), QStringLiteral("model-selection"), QStringLiteral("session-messages"), QStringLiteral("terminal-state"), QStringLiteral("workspace-files"), QStringLiteral("workspace-changes")}; }
inline QJsonObject commands() { return {
{QStringLiteral("hello"), QJsonObject{{QStringLiteral("client_id"), QStringLiteral("string")}, {QStringLiteral("major"), QStringLiteral("integer")}, {QStringLiteral("minor"), QStringLiteral("integer")}, {QStringLiteral("capabilities"), QStringLiteral("array")}}},
{QStringLiteral("daemon.status"), QJsonObject{}},
{QStringLiteral("daemon.shutdown"), QJsonObject{}},
{QStringLiteral("model.list"), QJsonObject{}},
{QStringLiteral("model.current"), QJsonObject{}},
{QStringLiteral("session.list"), QJsonObject{}},
{QStringLiteral("session.create"), QJsonObject{{QStringLiteral("title"), QStringLiteral("string")}}},
{QStringLiteral("session.attach"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("chat.send"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("text"), QStringLiteral("string")}}},
{QStringLiteral("agent.start"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("text"), QStringLiteral("string")}}},
{QStringLiteral("run.cancel"), QJsonObject{{QStringLiteral("run_id"), QStringLiteral("string")}}},
{QStringLiteral("approval.respond"), QJsonObject{{QStringLiteral("run_id"), QStringLiteral("string")}, {QStringLiteral("approval_id"), QStringLiteral("string")}, {QStringLiteral("allow"), QStringLiteral("boolean")}}},
{QStringLiteral("desktop.projection"), QJsonObject{{QStringLiteral("page"), QStringLiteral("integer")}}},
{QStringLiteral("desktop.action"), QJsonObject{{QStringLiteral("action"), QStringLiteral("string")}, {QStringLiteral("arguments"), QStringLiteral("array")}, {QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("session.messages"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("model.select"), QJsonObject{{QStringLiteral("provider_id"), QStringLiteral("string")}, {QStringLiteral("model_id"), QStringLiteral("string")}}},
{QStringLiteral("chat.regenerate"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("message_id"), QStringLiteral("integer")}}},
{QStringLiteral("chat.retry"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("message_id"), QStringLiteral("integer")}}},
{QStringLiteral("chat.edit"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}, {QStringLiteral("message_id"), QStringLiteral("integer")}, {QStringLiteral("text"), QStringLiteral("string")}}},
{QStringLiteral("desktop.settings"), QJsonObject{}},
{QStringLiteral("desktop.setting"), QJsonObject{{QStringLiteral("key"), QStringLiteral("string")}, {QStringLiteral("value"), QStringLiteral("string")}}},
{QStringLiteral("model.helper_state"), QJsonObject{{QStringLiteral("component"), QStringLiteral("string")}}},
{QStringLiteral("model.helper_action"), QJsonObject{{QStringLiteral("component"), QStringLiteral("string")}, {QStringLiteral("action"), QStringLiteral("string")}, {QStringLiteral("value"), QStringLiteral("string")}}},
{QStringLiteral("desktop.settings_service"), QJsonObject{{QStringLiteral("action"), QStringLiteral("string")}, {QStringLiteral("arguments"), QStringLiteral("array")}}},
{QStringLiteral("terminal.state"), QJsonObject{}},
{QStringLiteral("workspace.files"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("workspace.select"), QJsonObject{{QStringLiteral("workspace_id"), QStringLiteral("string")}}},
{QStringLiteral("workspace.root"), QJsonObject{{QStringLiteral("workspace_id"), QStringLiteral("string")}, {QStringLiteral("path"), QStringLiteral("string")}}},
{QStringLiteral("workspace.changes"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("workspace.create"), QJsonObject{{QStringLiteral("name"), QStringLiteral("string")}, {QStringLiteral("template"), QStringLiteral("string")}}},
{QStringLiteral("provider.select"), QJsonObject{{QStringLiteral("provider_id"), QStringLiteral("string")}}},
{QStringLiteral("terminal.attach"), QJsonObject{{QStringLiteral("session_id"), QStringLiteral("string")}}},
{QStringLiteral("voice.state"), QJsonObject{}},
{QStringLiteral("voice.action"), QJsonObject{{QStringLiteral("action"), QStringLiteral("string")}}},
{QStringLiteral("voice.audio"), QJsonObject{{QStringLiteral("pcm"), QStringLiteral("string")}, {QStringLiteral("final"), QStringLiteral("boolean")}, {QStringLiteral("speech"), QStringLiteral("boolean")}}},
}; }
}
// clang-format on
