// Generated by tools/ipc/generate.py; do not edit.
pub const MAJOR: usize = 1;
pub const MINOR: usize = 1;
pub const MAX_FRAME_BYTES: usize = 262144;
pub const MAX_PENDING_BYTES: usize = 1048576;
pub const COMMANDS: &[(&str, &[(&str, &str)])] = &[
("hello", &[("client_id", "string"), ("major", "integer"), ("minor", "integer"), ("capabilities", "array")]),
("daemon.status", &[]),
("daemon.shutdown", &[]),
("model.list", &[]),
("model.current", &[]),
("session.list", &[]),
("session.create", &[("title", "string")]),
("session.attach", &[("session_id", "string")]),
("chat.send", &[("session_id", "string"), ("text", "string")]),
("agent.start", &[("session_id", "string"), ("text", "string")]),
("run.cancel", &[("run_id", "string")]),
("approval.respond", &[("run_id", "string"), ("approval_id", "string"), ("allow", "boolean")]),
("desktop.projection", &[("page", "integer")]),
("desktop.action", &[("action", "string"), ("arguments", "array"), ("session_id", "string")]),
("session.messages", &[("session_id", "string")]),
("model.select", &[("provider_id", "string"), ("model_id", "string")]),
("chat.regenerate", &[("session_id", "string"), ("message_id", "integer")]),
("chat.retry", &[("session_id", "string"), ("message_id", "integer")]),
("chat.edit", &[("session_id", "string"), ("message_id", "integer"), ("text", "string")]),
("desktop.settings", &[]),
("desktop.setting", &[("key", "string"), ("value", "string")]),
("model.helper_state", &[("component", "string")]),
("model.helper_action", &[("component", "string"), ("action", "string"), ("value", "string")]),
("desktop.settings_service", &[("action", "string"), ("arguments", "array")]),
("terminal.state", &[]),
("workspace.files", &[("session_id", "string")]),
("workspace.select", &[("workspace_id", "string")]),
("workspace.root", &[("workspace_id", "string"), ("path", "string")]),
("workspace.changes", &[("session_id", "string")]),
("workspace.create", &[("name", "string"), ("template", "string")]),
("provider.select", &[("provider_id", "string")]),
("terminal.attach", &[("session_id", "string")]),
("voice.state", &[]),
("voice.action", &[("action", "string")]),
("voice.audio", &[("pcm", "string"), ("final", "boolean"), ("speech", "boolean")]),
("agent.history", &[("run_id", "string"), ("before_time", "string"), ("before_id", "string")]),
("backup.transfer", &[("action", "string"), ("value", "object")]),
];
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "name", content = "payload")]
pub enum RequestPayload {
#[serde(rename = "hello")]
Hello {client_id: String, major: u64, minor: u64, capabilities: Vec<serde_json::Value>},
#[serde(rename = "daemon.status")]
DaemonStatus {},
#[serde(rename = "daemon.shutdown")]
DaemonShutdown {},
#[serde(rename = "model.list")]
ModelList {},
#[serde(rename = "model.current")]
ModelCurrent {},
#[serde(rename = "session.list")]
SessionList {},
#[serde(rename = "session.create")]
SessionCreate {title: String},
#[serde(rename = "session.attach")]
SessionAttach {session_id: String},
#[serde(rename = "chat.send")]
ChatSend {session_id: String, text: String, #[serde(default)] attachments: Option<Vec<serde_json::Value>>},
#[serde(rename = "agent.start")]
AgentStart {session_id: String, text: String, #[serde(default)] attachments: Option<Vec<serde_json::Value>>},
#[serde(rename = "run.cancel")]
RunCancel {run_id: String},
#[serde(rename = "approval.respond")]
ApprovalRespond {run_id: String, approval_id: String, allow: bool},
#[serde(rename = "desktop.projection")]
DesktopProjection {page: u64},
#[serde(rename = "desktop.action")]
DesktopAction {action: String, arguments: Vec<serde_json::Value>, session_id: String},
#[serde(rename = "session.messages")]
SessionMessages {session_id: String},
#[serde(rename = "model.select")]
ModelSelect {provider_id: String, model_id: String},
#[serde(rename = "chat.regenerate")]
ChatRegenerate {session_id: String, message_id: u64},
#[serde(rename = "chat.retry")]
ChatRetry {session_id: String, message_id: u64},
#[serde(rename = "chat.edit")]
ChatEdit {session_id: String, message_id: u64, text: String},
#[serde(rename = "desktop.settings")]
DesktopSettings {},
#[serde(rename = "desktop.setting")]
DesktopSetting {key: String, value: String},
#[serde(rename = "model.helper_state")]
ModelHelperState {component: String, #[serde(default)] offset: Option<u64>},
#[serde(rename = "model.helper_action")]
ModelHelperAction {component: String, action: String, value: String},
#[serde(rename = "desktop.settings_service")]
DesktopSettingsService {action: String, arguments: Vec<serde_json::Value>},
#[serde(rename = "terminal.state")]
TerminalState {},
#[serde(rename = "workspace.files")]
WorkspaceFiles {session_id: String},
#[serde(rename = "workspace.select")]
WorkspaceSelect {workspace_id: String},
#[serde(rename = "workspace.root")]
WorkspaceRoot {workspace_id: String, path: String},
#[serde(rename = "workspace.changes")]
WorkspaceChanges {session_id: String},
#[serde(rename = "workspace.create")]
WorkspaceCreate {name: String, template: String},
#[serde(rename = "provider.select")]
ProviderSelect {provider_id: String},
#[serde(rename = "terminal.attach")]
TerminalAttach {session_id: String},
#[serde(rename = "voice.state")]
VoiceState {},
#[serde(rename = "voice.action")]
VoiceAction {action: String},
#[serde(rename = "voice.audio")]
VoiceAudio {pcm: String, r#final: bool, speech: bool},
#[serde(rename = "agent.history")]
AgentHistory {run_id: String, before_time: String, before_id: String},
#[serde(rename = "backup.transfer")]
BackupTransfer {action: String, value: serde_json::Value},
}
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "name", content = "payload")]
pub enum ResponsePayload {
#[serde(rename = "hello")]
Hello {major: u64, minor: u64, daemon_version: String, capabilities: Vec<serde_json::Value>, #[serde(default)] server_generation: Option<String>},
#[serde(rename = "daemon.status")]
DaemonStatus {running: bool, daemon_version: String, uptime_ms: u64, active_runs: u64, sessions: u64, #[serde(default)] protocol_major: Option<u64>, #[serde(default)] protocol_minor: Option<u64>, #[serde(default)] endpoint: Option<String>, #[serde(default)] server_generation: Option<String>},
#[serde(rename = "daemon.shutdown")]
DaemonShutdown {shutting_down: bool},
#[serde(rename = "model.list")]
ModelList {models: Vec<serde_json::Value>},
#[serde(rename = "model.current")]
ModelCurrent {provider_id: String, model_id: String},
#[serde(rename = "session.list")]
SessionList {sessions: Vec<serde_json::Value>},
#[serde(rename = "session.create")]
SessionCreate {session_id: String, r#type: String, created_at: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] properties: Option<serde_json::Value>, #[serde(default)] run_id: Option<String>, #[serde(default)] run_type: Option<String>, #[serde(default)] provider_id: Option<String>, #[serde(default)] model_id: Option<String>, #[serde(default)] state: Option<String>, #[serde(default)] output: Option<String>, #[serde(default)] output_truncated: Option<bool>, #[serde(default)] approval_id: Option<String>, #[serde(default)] approval: Option<serde_json::Value>, #[serde(default)] title: Option<String>, #[serde(default)] summary: Option<String>, #[serde(default)] pinned: Option<bool>, #[serde(default)] archived: Option<bool>, #[serde(default)] conversation_id: Option<String>, #[serde(default)] detail: Option<String>},
#[serde(rename = "session.attach")]
SessionAttach {session_id: String, state: String, output: String, run_id: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] properties: Option<serde_json::Value>, #[serde(default)] run_type: Option<String>, #[serde(default)] provider_id: Option<String>, #[serde(default)] model_id: Option<String>, #[serde(default)] output_truncated: Option<bool>, #[serde(default)] approval_id: Option<String>, #[serde(default)] approval: Option<serde_json::Value>, #[serde(default)] title: Option<String>, #[serde(default)] summary: Option<String>, #[serde(default)] pinned: Option<bool>, #[serde(default)] archived: Option<bool>, #[serde(default)] conversation_id: Option<String>, #[serde(default)] created_at: Option<String>, #[serde(default)] r#type: Option<String>, #[serde(default)] detail: Option<String>},
#[serde(rename = "chat.send")]
ChatSend {session_id: String, run_id: String},
#[serde(rename = "agent.start")]
AgentStart {session_id: String, run_id: String},
#[serde(rename = "run.cancel")]
RunCancel {accepted: bool},
#[serde(rename = "approval.respond")]
ApprovalRespond {accepted: bool},
#[serde(rename = "desktop.projection")]
DesktopProjection {page: u64, pages: u64, properties: serde_json::Value},
#[serde(rename = "desktop.action")]
DesktopAction {accepted: bool, result: serde_json::Value},
#[serde(rename = "session.messages")]
SessionMessages {session_id: String, messages: Vec<serde_json::Value>},
#[serde(rename = "model.select")]
ModelSelect {provider_id: String, model_id: String},
#[serde(rename = "chat.regenerate")]
ChatRegenerate {session_id: String, run_id: String},
#[serde(rename = "chat.retry")]
ChatRetry {session_id: String, run_id: String},
#[serde(rename = "chat.edit")]
ChatEdit {session_id: String, run_id: String},
#[serde(rename = "desktop.settings")]
DesktopSettings {values: serde_json::Value},
#[serde(rename = "desktop.setting")]
DesktopSetting {accepted: bool},
#[serde(rename = "model.helper_state")]
ModelHelperState {component: String, properties: serde_json::Value},
#[serde(rename = "model.helper_action")]
ModelHelperAction {accepted: bool},
#[serde(rename = "desktop.settings_service")]
DesktopSettingsService {result: serde_json::Value},
#[serde(rename = "terminal.state")]
TerminalState {properties: serde_json::Value, providers: Vec<serde_json::Value>, workspace: serde_json::Value, workspaces: Vec<serde_json::Value>},
#[serde(rename = "workspace.files")]
WorkspaceFiles {files: Vec<serde_json::Value>, truncated: bool, root: String},
#[serde(rename = "workspace.select")]
WorkspaceSelect {workspace_id: String},
#[serde(rename = "workspace.root")]
WorkspaceRoot {workspace_id: String, root: String},
#[serde(rename = "workspace.changes")]
WorkspaceChanges {available: bool, files: Vec<serde_json::Value>, truncated: bool, #[serde(default)] root: Option<String>, #[serde(default)] reason: Option<String>},
#[serde(rename = "workspace.create")]
WorkspaceCreate {workspace_id: String},
#[serde(rename = "provider.select")]
ProviderSelect {provider_id: String, model_id: String},
#[serde(rename = "terminal.attach")]
TerminalAttach {session_id: String, state: String, output: String, run_id: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] properties: Option<serde_json::Value>, #[serde(default)] run_type: Option<String>, #[serde(default)] provider_id: Option<String>, #[serde(default)] model_id: Option<String>, #[serde(default)] output_truncated: Option<bool>, #[serde(default)] approval_id: Option<String>, #[serde(default)] approval: Option<serde_json::Value>, #[serde(default)] title: Option<String>, #[serde(default)] summary: Option<String>, #[serde(default)] pinned: Option<bool>, #[serde(default)] archived: Option<bool>, #[serde(default)] conversation_id: Option<String>, #[serde(default)] created_at: Option<String>, #[serde(default)] r#type: Option<String>, #[serde(default)] detail: Option<String>},
#[serde(rename = "voice.state")]
VoiceState {state: String, available: bool, owned: bool, transcript: String, failure: String, input_device_id: String, vad_enabled: bool},
#[serde(rename = "voice.action")]
VoiceAction {accepted: bool},
#[serde(rename = "voice.audio")]
VoiceAudio {accepted: bool},
#[serde(rename = "agent.history")]
AgentHistory {history: serde_json::Value},
#[serde(rename = "backup.transfer")]
BackupTransfer {result: serde_json::Value},
}
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "name", content = "payload")]
pub enum EventPayload {
#[serde(rename = "run.started")]
RunStarted {run_id: String, session_id: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>},
#[serde(rename = "output.delta")]
OutputDelta {run_id: String, session_id: String, text: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>},
#[serde(rename = "tool.requested")]
ToolRequested {run_id: String, session_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] tool_call_id: Option<String>, #[serde(default)] timestamp: Option<String>, #[serde(default)] state: Option<String>},
#[serde(rename = "approval.requested")]
ApprovalRequested {run_id: String, session_id: String, approval_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] state: Option<String>},
#[serde(rename = "tool.result")]
ToolResult {run_id: String, session_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] tool_call_id: Option<String>, #[serde(default)] timestamp: Option<String>, #[serde(default)] state: Option<String>, #[serde(default)] duration_ms: Option<u64>},
#[serde(rename = "run.completed")]
RunCompleted {run_id: String, session_id: String, text: String, state: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>},
#[serde(rename = "run.failed")]
RunFailed {run_id: String, session_id: String, text: String, state: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>},
#[serde(rename = "run.cancelled")]
RunCancelled {run_id: String, session_id: String, text: String, state: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>},
#[serde(rename = "agent.activity")]
AgentActivity {run_id: String, session_id: String, activity: String, step: u64, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] decision: Option<String>},
#[serde(rename = "tool.running")]
ToolRunning {run_id: String, session_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>, #[serde(default)] tool_call_id: Option<String>, #[serde(default)] timestamp: Option<String>, #[serde(default)] state: Option<String>},
#[serde(rename = "subagent.activity")]
SubagentActivity {run_id: String, session_id: String, subagent_id: String, parent_run_id: String, role: String, state: String, #[serde(default)] server_generation: Option<String>, #[serde(default)] event_sequence: Option<u64>},
}
pub const CAPABILITIES: &[&str] = &["chat","agent","approval","sessions","events","desktop-projection","model-selection","session-messages","terminal-state","workspace-files","workspace-changes"];
pub const EVENTS: &[&str] = &["run.started","output.delta","tool.requested","approval.requested","tool.result","run.completed","run.failed","run.cancelled","agent.activity","tool.running","subagent.activity"];
