// Generated by tools/ipc/generate.py; do not edit.
pub const MAJOR: usize = 1;
pub const MINOR: usize = 0;
pub const MAX_FRAME_BYTES: usize = 262144;
pub const MAX_PENDING_BYTES: usize = 1048576;
pub const COMMANDS: &[(&str, &[(&str, &str)])] = &[
("hello", &[("client_id", "string"), ("major", "integer"), ("minor", "integer"), ("capabilities", "array")]),
("daemon.status", &[]),
("daemon.shutdown", &[]),
("model.list", &[]),
("model.current", &[]),
("session.list", &[]),
("session.create", &[("title", "string")]),
("session.attach", &[("session_id", "string")]),
("chat.send", &[("session_id", "string"), ("text", "string")]),
("agent.start", &[("session_id", "string"), ("text", "string")]),
("run.cancel", &[("run_id", "string")]),
("approval.respond", &[("run_id", "string"), ("approval_id", "string"), ("allow", "boolean")]),
];
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "name", content = "payload")]
pub enum RequestPayload {
#[serde(rename = "hello")]
Hello {client_id: String, major: u64, minor: u64, capabilities: Vec<serde_json::Value>},
#[serde(rename = "daemon.status")]
DaemonStatus {},
#[serde(rename = "daemon.shutdown")]
DaemonShutdown {},
#[serde(rename = "model.list")]
ModelList {},
#[serde(rename = "model.current")]
ModelCurrent {},
#[serde(rename = "session.list")]
SessionList {},
#[serde(rename = "session.create")]
SessionCreate {title: String},
#[serde(rename = "session.attach")]
SessionAttach {session_id: String},
#[serde(rename = "chat.send")]
ChatSend {session_id: String, text: String},
#[serde(rename = "agent.start")]
AgentStart {session_id: String, text: String},
#[serde(rename = "run.cancel")]
RunCancel {run_id: String},
#[serde(rename = "approval.respond")]
ApprovalRespond {run_id: String, approval_id: String, allow: bool},
}
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "name", content = "payload")]
pub enum ResponsePayload {
#[serde(rename = "hello")]
Hello {major: u64, minor: u64, daemon_version: String, capabilities: Vec<serde_json::Value>},
#[serde(rename = "daemon.status")]
DaemonStatus {running: bool, daemon_version: String, uptime_ms: u64, active_runs: u64, sessions: u64},
#[serde(rename = "daemon.shutdown")]
DaemonShutdown {shutting_down: bool},
#[serde(rename = "model.list")]
ModelList {models: Vec<serde_json::Value>},
#[serde(rename = "model.current")]
ModelCurrent {provider_id: String, model_id: String},
#[serde(rename = "session.list")]
SessionList {sessions: Vec<serde_json::Value>},
#[serde(rename = "session.create")]
SessionCreate {session_id: String, r#type: String, created_at: String},
#[serde(rename = "session.attach")]
SessionAttach {session_id: String, state: String, output: String, run_id: String},
#[serde(rename = "chat.send")]
ChatSend {session_id: String, run_id: String},
#[serde(rename = "agent.start")]
AgentStart {session_id: String, run_id: String},
#[serde(rename = "run.cancel")]
RunCancel {accepted: bool},
#[serde(rename = "approval.respond")]
ApprovalRespond {accepted: bool},
}
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "name", content = "payload")]
pub enum EventPayload {
#[serde(rename = "run.started")]
RunStarted {run_id: String, session_id: String},
#[serde(rename = "output.delta")]
OutputDelta {run_id: String, session_id: String, text: String},
#[serde(rename = "tool.requested")]
ToolRequested {run_id: String, session_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>},
#[serde(rename = "approval.requested")]
ApprovalRequested {run_id: String, session_id: String, approval_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>},
#[serde(rename = "tool.result")]
ToolResult {run_id: String, session_id: String, tool: String, detail: String, risk: u64, resources: Vec<serde_json::Value>},
#[serde(rename = "run.completed")]
RunCompleted {run_id: String, session_id: String, text: String, state: String},
#[serde(rename = "run.failed")]
RunFailed {run_id: String, session_id: String, text: String, state: String},
#[serde(rename = "run.cancelled")]
RunCancelled {run_id: String, session_id: String, text: String, state: String},
}
pub const CAPABILITIES: &[&str] = &["chat","agent","approval","sessions","events"];
pub const EVENTS: &[&str] = &["run.started","output.delta","tool.requested","approval.requested","tool.result","run.completed","run.failed","run.cancelled"];
